// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: main.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TellAboutPhotoClient is the client API for TellAboutPhoto service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TellAboutPhotoClient interface {
	GetInfo(ctx context.Context, in *TellRequest, opts ...grpc.CallOption) (*TellResponse, error)
}

type tellAboutPhotoClient struct {
	cc grpc.ClientConnInterface
}

func NewTellAboutPhotoClient(cc grpc.ClientConnInterface) TellAboutPhotoClient {
	return &tellAboutPhotoClient{cc}
}

func (c *tellAboutPhotoClient) GetInfo(ctx context.Context, in *TellRequest, opts ...grpc.CallOption) (*TellResponse, error) {
	out := new(TellResponse)
	err := c.cc.Invoke(ctx, "/proto.TellAboutPhoto/GetInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TellAboutPhotoServer is the server API for TellAboutPhoto service.
// All implementations must embed UnimplementedTellAboutPhotoServer
// for forward compatibility
type TellAboutPhotoServer interface {
	GetInfo(context.Context, *TellRequest) (*TellResponse, error)
	mustEmbedUnimplementedTellAboutPhotoServer()
}

// UnimplementedTellAboutPhotoServer must be embedded to have forward compatible implementations.
type UnimplementedTellAboutPhotoServer struct {
}

func (UnimplementedTellAboutPhotoServer) GetInfo(context.Context, *TellRequest) (*TellResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedTellAboutPhotoServer) mustEmbedUnimplementedTellAboutPhotoServer() {}

// UnsafeTellAboutPhotoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TellAboutPhotoServer will
// result in compilation errors.
type UnsafeTellAboutPhotoServer interface {
	mustEmbedUnimplementedTellAboutPhotoServer()
}

func RegisterTellAboutPhotoServer(s grpc.ServiceRegistrar, srv TellAboutPhotoServer) {
	s.RegisterService(&TellAboutPhoto_ServiceDesc, srv)
}

func _TellAboutPhoto_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TellRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TellAboutPhotoServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TellAboutPhoto/GetInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TellAboutPhotoServer).GetInfo(ctx, req.(*TellRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TellAboutPhoto_ServiceDesc is the grpc.ServiceDesc for TellAboutPhoto service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TellAboutPhoto_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TellAboutPhoto",
	HandlerType: (*TellAboutPhotoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _TellAboutPhoto_GetInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "main.proto",
}
