# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: main.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmain.proto\x12\x05proto\"1\n\x0cMediaRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x13\n\x0b\x63ontentType\x18\x02 \x01(\t\";\n\x0bTellRequest\x12,\n\x0fmediaTellReqArr\x18\x01 \x03(\x0b\x32\x13.proto.MediaRequest\"G\n\rMediaResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x13\n\x0b\x63ontentType\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"V\n\x0cTellResponse\x12.\n\x10mediaTellRespArr\x18\x01 \x03(\x0b\x32\x14.proto.MediaResponse\x12\x16\n\x0e\x64\x65scriptionAll\x18\x02 \x01(\t2F\n\x0eTellAboutPhoto\x12\x34\n\x07GetInfo\x12\x12.proto.TellRequest\x1a\x13.proto.TellResponse\"\x00\x42\rZ\x0b\x61pp2/proto2b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'main_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\013app2/proto2'
  _MEDIAREQUEST._serialized_start=21
  _MEDIAREQUEST._serialized_end=70
  _TELLREQUEST._serialized_start=72
  _TELLREQUEST._serialized_end=131
  _MEDIARESPONSE._serialized_start=133
  _MEDIARESPONSE._serialized_end=204
  _TELLRESPONSE._serialized_start=206
  _TELLRESPONSE._serialized_end=292
  _TELLABOUTPHOTO._serialized_start=294
  _TELLABOUTPHOTO._serialized_end=364
# @@protoc_insertion_point(module_scope)
